
const n1 =28;
const n3 =29;

console.log(n1);

try {
    console.log(n2);
} catch (error) {
    console.log(error);
}
console.log(n3);
